# Don't print a new line at the start of the prompt
add_newline = false

# GIT
[git_branch]
symbol = "ğŸŒ± "
# truncation_length = 10
# truncation_symbol = ""

[git_commit]
commit_hash_length = 4

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "ğŸ’ PICKING"

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged.value = "++"
staged.style = "green"
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[conda]
style = "dimmed green"

[crystal]
symbol = "âœ¨ "
style = "bold blue"

[docker_context]
symbol = "ğŸ‹ "

[dotnet]
symbol = "ğŸ¥… "
style = "green"
heuristic = false

[elixir]
symbol = "ğŸ”® "

[elm]
symbol = "î˜¬ "

[env_var]
variable = "SHELL"
default = "unknown shell"

[erlang]
symbol = "e "

[golang]
symbol = "ğŸğŸ’¨ "

[jobs]
symbol = "+ "
threshold = 4

[julia]
symbol = "âˆ´ "

[nim]
style = "yellow"
symbol = "ğŸ£ "

[nodejs]
symbol = "ğŸ¤– "

[package]
symbol = "ğŸ "

[ocaml]
symbol = "ğŸª "

[php]
symbol = "ğŸ”¹ "

[singularity]
symbol = "ğŸ“¦ "

[terraform]
symbol = "ğŸğŸ’¨ "

[username]
disabled = false

[zig]
symbol = "âš¡ï¸ "

[ruby]
symbol = "ğŸ”º "

[rust]
symbol = "âš™ï¸ "

[java]
symbol = "ğŸŒŸ "

[hostname]
ssh_only = true
format =  "on [$hostname](bold red) "
trim_at = ".local"
disabled = false

[aws]
style = "bold blue"
symbol = "ğŸ…° "
format = 'on [$symbol($profile )(\($region\) )]($style)'
[aws.region_aliases]
ap-southeast-2 = "au"
us-east-1 = "va"

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"

[character]
# symbol = "âœ"
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ—](bold red) "

